echo -e "\n ${RED}Check data usage & docker directory size before clean-up ${NC}\n"
#Check data usage before clean-up
df
#Check docker directory size before clean-up
cd /var/lib/docker/
du -d 1 -h

#Stop all containers
sudo docker stop $(docker ps -a -q)

#Remove any stopped containers and all unused images
sudo docker system prune -a 

#Stop docker 
sudo systemctl stop docker

#Remove context of volumes folder in docker (data generated by containers)
sudo rm -r /var/lib/docker/volumes/*
#Remove context of overlay2 folder in docker (containers read/write layer. Variables for containers)
sudo rm -r /var/lib/docker/overlay2/*

#The correct way to start docker is to use systemd/systemctl
sudo systemctl enable docker
sudo systemctl start docker

echo -e "\n ${RED}Check data usage & docker directory size after clean-up ${NC}\n"
#Check data usage after clean-up
df
#Check docker directory size after clean-up
cd /var/lib/docker/
du -d 1 -h
